version: '3.8'

services:
  mariadb:
    build: .
    restart: always
    container_name: mariadb_container
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - mariadb_network

  express-server:
    build:
      context: ./server
      args:
        - DATABASE_URL=${DATABASE_URL}
    container_name: express_server_container
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - mariadb_network
    depends_on:
      - mariadb
    command: >
      sh -c './wait-for-it.sh mariadb:${DATABASE_PORT} -- npx prisma migrate deploy && npx prisma db seed && npm start'

  client:
    build: ./client
    container_name: client_container
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - mariadb_network
    depends_on:
      - express-server

volumes:
  mariadb_data:

networks:
  mariadb_network:
